### ISSUE TITLE
Error install with composer

### ISSUE THREAD

**Issue by Ruriko** [saeedvaziry/ibio#4]
Here are my steps on how I tried to install:
```
git clone https://github.com/saeedvaziry/ibio
cp .env.example .env
php7.4 /usr/local/bin/composer install && npm install && npm run dev

```
then I get error:
```
> @ dev /var/www/bio.adoreanime.com/htdocs/ibio
> npm run development


> @ development /var/www/bio.adoreanime.com/htdocs/ibio
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'tailwindcss'
Require stack:
- /var/www/bio.adoreanime.com/htdocs/ibio/webpack.mix.js
- /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/laravel-mix/setup/webpack.config.js
- /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js
- /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js
- /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/var/www/bio.adoreanime.com/htdocs/ibio/webpack.mix.js:18:9)
    at Module._compile (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
    at /var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/bio.adoreanime.com/htdocs/ibio/webpack.mix.js',
    '/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/laravel-mix/setup/webpack.config.js',
    '/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack-cli/bin/cli.js',
    '/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-13T12_51_38_767Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-13T12_51_38_820Z-debug.log

```

debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/bio.adoreanime.com/htdocs/ibio/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~dev: CWD: /var/www/bio.adoreanime.com/htdocs/ibio
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @
15 verbose cwd /var/www/bio.adoreanime.com/htdocs/ibio
16 verbose Linux 5.4.0-88-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
What is the problem?

**Comment by saeedvaziry** [comment]
remove the `yarn.lock` and `node_modules` folder and then run `yarn install`
